name: Website Deployment
on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v6
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      # skip the installation if there is a chache hit.
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit == 'false'
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v6
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      # skip the installation if there is a chache hit.
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit == 'false'
        run: npm ci
      - name: Test code
        id: run-tests
        run: npm run test
      # we only should upload the test report if the Test Code step failed
      - name: Upload test report
        # failure() => when any pervoius step or job failed.
        # this is a special function to force the triggering of this step even if the pervoius one failed.
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v6
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      # skip the installation if there is a chache hit.
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit == 'false'
        run: npm ci
      - name: Build website
        id: build-website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v8
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."

  report:
    needs: [deploy,lint]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output Information 
        run: echo "Something went wrong !!"
