name: Get newly created Issues Meta data
on: 
  issues:
    types: [opened]
jobs:
  Output_the_Event_details:
    runs-on: ubuntu-latest
    steps:
      - name: Print the Issue Event meta data
        run: echo "${{github.event}}"
      - name: Print github meta data  
        run: echo "${{github}}"