name: Get newly created Issues Meta data
on: 
  issues:
    types: [opened]
jobs:
  Output_the_Event_details:
    runs-on: ubuntu-latest
    steps:
      - name: Print the Issue Event meta data
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$EVENT_CONTEXT"

      - name: Print github meta data  
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"