name: Test_Deploy
# This workflow would be triggered when Commit Push happened or manually(using github GUI or github APIs).
on: 
  push:
    branches:
      - 'master'
jobs:
  # Performing the static and dynamic testing togther in one job
  lint_test:
    runs-on: ubuntu-latest
    steps:
      # init the test environment Tools versions
      - name: setup the needed nodeJs version on the Runner
        uses: actions/setup-node@v7
        with:
          node-version: 'latest'
      # The repo source code doesn't exist by default on the Runner.
      # it mandatory to checkout the repo to access the source code and even the test cases.
      - name: Checkout the repo on the Runner
        uses: actions/checkout@v7
      # Install all the SW packages which are needed to build and run the application and the test suit
      - name: Install the Project dependencies 
        run: npm ci
      # Run the static anlysis tests on the App
      - name: Run Lint on the Project
        run: npm run lint
      # Run the dynamic test cases on the App
      - name: Run Test on the Project
        run: npm run test
  build:
    needs: lint_test
    runs-on: ubuntu-latest
    output:
      script-file: ${{steps.Publish.outputs.script_file}}
    steps:
    - name: Checkout the repo on the Runner
      uses: actions/checkout@v7
    # Install all the SW packages which are needed to build and run the application and the test suit
    - name: Install the Project dependencies 
      run: npm ci
    - name: Build the application to deploy
      run: npm run build
    # upload the generated build artifacts from the build command.
    - name: Upload the job artifacts
      uses: actions/upload-artifact@v7
      with:
        # we must set an artifact identifier to use it later in the download artifact jobs
        name: build_artifacts
        path: dist 
    # Generate the generated file name as a job output
    - name: Publish the JS generated file name in the build artifacts
      id: Publish
      run: find dist/assets/*.js -type f -execdir echo 'script_file={}' >> $GITHUB_OUTPUT ';'
  # this CI Job would run after this job "lint_test" to be executed and finished without any error or failures.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: setup the needed nodeJs version on the Runner
        uses: actions/setup-node@v7
        with:
          node-version: 'latest'

      - name: Download the production build artifacts
        uses: actions/download-artifact@v7
        with:
          name: build_artifacts
      - name: list all the folder and files in the current location on the runner
        run: ls
      - name: output the generated file name by the last job
        run: echo "the generated file name in the build job is ${{needs.build.outputs.script-file}}"

      - name: Deploy the application on the Production Server
        run: echo "Deploying the application on the Server......."


