name: Test_Deploy
on: [workflow_dispatch,push]
jobs:
  # Performing the static and dynamic testing togther in one job
  lint_test_job:
  runs-on: ubuntu-latest
  steps:
    - name: setup the needed nodeJs version on the Runner
      uses: actions/setup-node@v7
      with:
        node-version: '22.22.2'
    
    - name: Checkout the repo on the Runner
      uses: actions/checkout@v7

    - name: Run Lint on the Project
      run: npm lint

    - name: Run Test on the Project
      run: npm test
  
  deploy_job:
  needs: lint_test_job
  runs-on: ubuntu-latest
  steps:
    - name: setup the needed nodeJs version on the Runner
      uses: actions/setup-node@v7
      with:
        node-version: '22.22.2'
    
    - name: Checkout the repo on the Runner
      uses: actions/checkout@v7

    - name: Build the application to deploy
      run: npm build

    - name: Deploy the application on the Production Server
      run: echo "Deploying the application on the Server......."


