name: use_workfolw
on: 
  push:
    branches:
      - master
jobs:
  Call_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repo code on the Runner
        use: actions/checkout@v7
      - name: call existing workflow_call 
        uses: ./.github/workflows/reusable.yaml
